// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFI98W7DPBc91E9Z45PIBmOR3G14_j9s',
    appId: '1:67200924558:web:414993f9508af62b2cc2df',
    messagingSenderId: '67200924558',
    projectId: 'joby-af0c9',
    authDomain: 'joby-af0c9.firebaseapp.com',
    storageBucket: 'joby-af0c9.firebasestorage.app',
    measurementId: 'G-CDFRKCHV69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdpBopHE_TRM6x56PPoTSinqmdBYoCLOY',
    appId: '1:67200924558:android:26c6d04868203e932cc2df',
    messagingSenderId: '67200924558',
    projectId: 'joby-af0c9',
    storageBucket: 'joby-af0c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgkEX8UuTXVFt8d1uRMwddP_LYzYT7l24',
    appId: '1:67200924558:ios:b4e8476209ef1dbc2cc2df',
    messagingSenderId: '67200924558',
    projectId: 'joby-af0c9',
    storageBucket: 'joby-af0c9.firebasestorage.app',
    iosBundleId: 'ee.efficio.joby.joby',
  );
}
