// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBvT3Q6q2pt7nW_72_TG2z2O7-Li6QngVk",
    authDomain: "joby-af0c9.firebaseapp.com",
    projectId: "joby-af0c9",
    storageBucket: "joby-af0c9.firebasestorage.app",
    messagingSenderId: "67200924558",
    appId: "1:67200924558:web:414993f9508af62b2cc2df",
    measurementId: "G-CDFRKCHV69",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2rF0RpLPFCJstmWCYOOPNDkEsDrXpp8c',
    appId: '1:67200924558:android:26c6d04868203e932cc2df',
    messagingSenderId: '67200924558',
    projectId: 'joby-af0c9',
    storageBucket: 'joby-af0c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy8cX2_yUy9U7cgqPPMFbe57SqvvD38r4',
    appId: '1:67200924558:ios:b4e8476209ef1dbc2cc2df',
    messagingSenderId: '67200924558',
    projectId: 'joby-af0c9',
    storageBucket: 'joby-af0c9.firebasestorage.app',
    iosBundleId: 'ee.efficio.joby.joby',
  );
}
